### ISSUE TITLE
How can we change the URL of the Kinesis server?

### ISSUE THREAD

**Issue by jalara** [monetate/koupler#46]
Where in this repository/project can we modify the Kinesis endpoint similar to this:

```
client = new AmazonKinesisClient();
client.setEndpoint(endpoint, serviceName, regionId);
```

Thanks in advance!

**Comment by boneill42** [comment]
Have you tried setting the custom endpoint in the kpl.properties?
https://github.com/monetate/koupler/blob/master/conf/kpl.properties#L83
